backend:
  name: git-gateway
  branch: master
media_folder: "docs/src/.vuepress/public/"
public_folder: "../../"
display_url:
collections:
  - name: pages
    label: Pages
    folder: "hitowa"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true

    fields:
      - {name: title, widget: string}
      - {name: layout, widget: select, options: ['grid', 'full-width', 'about', 'contact']}
      - {label: "categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}

      - name: sections
        widget: list
        types:
          - name: text_section
            label: Text
            widget: object
            folder: "hitowa"
            slug: "{{slug}}"
            create: true
            fields: 
              - {label: "Body", name: "body", widget: "markdown"}

          - name: image_section
            label: Image
            widget: object
            folder: "hitowa"
            slug: "{{slug}}"
            create: true
            fields: 
              - {name: image, widget: image}
              - {name: background-color, widget: select, options: [Dark, Medium, Light], required: false}


          - name: slider_section
            label: Slider
            widget: object
            folder: "hitowa"
            slug: "{{slug}}"
            create: true
            preview: true
            fields:
              - name: images  
                widget: list
                field: {label: Image, name: image, widget: image}
              - {name: background-color, widget: select, options: [Dark, Medium, Light], required: false}

          - name: video_section
            label: Video
            widget: object
            folder: "hitowa"
            slug: "{{slug}}"
            create: true
            fields:
              - {name: embed, label: Embed video, hint: 'YouTube or Vimeo url'}
              - {name: background-color, widget: select, options: [Dark, Medium, Light], required: false}

